# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - uses: actions/cache@v3
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }} #-${{ hashFiles('dev-requirements.txt') }}

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        sudo apt install -y gcc cmake gperf libgmp-dev
        python -m pip install --upgrade pip
        pip install pytest
        /bin/bash setup.sh --no-gigahorse

    - name: Test with pytest
      run: |
        source venv/bin/activate
        cd tests
        pytest
        